name: pdf_merger_ocr_pdfa
description: App desktop mínima para unir PDFs con OCR, PDF/A e 200 dpi (límite 4GB).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.4.4
  file_selector: ^1.0.3
  path: ^1.9.0

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
